#ifndef H_GAME_FLAGS
#define H_GAME_FLAGS

//definition of global game flags index
#define GOT_CASSETTE        0
#define GOT_GUITAR          1
#define USED_COMPUTER       2
#define USED_CASSETTE       3
#define STEREO_ON           4

#define BATH_CLOSET_OPEN    5
#define BATH_DOOR_OPEN      6
#define GOT_GEL             7
#define BATH_MIRROR_MSG     8
#define BATH_LIGHT_OFF      9

#define CORRIDOR_MIRROR_MSG 10

#define PRINTED_SCHOOL_SCHEDULE 11
#define PRINTED_PHOTOCOPY       12

#define GOT_CLOCK               13
#endif //H_GAME_FLAGS
