/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\GDATA.DAT */
/* Date: Mon Sep 09 12:28:00 2024 */
/* Do not hand edit! */

#define gd_gamePal                       0        /* PAL  */
#define gd_cursor                        1        /* BMP  */
#define gd_hud                           2        /* BMP  */
#define gd_hudhs                         3        /* BMP  */
#define gd_hudGoSel                      4        /* BMP  */
#define gd_hudCloseSel                   5        /* BMP  */
#define gd_hudGiveSel                    6        /* BMP  */
#define gd_hudLookSel                    7        /* BMP  */
#define gd_hudMoveSel                    8        /* BMP  */
#define gd_hudOpenSel                    9        /* BMP  */
#define gd_hudTakeSel                    10       /* BMP  */
#define gd_hudTalkSel                    11       /* BMP  */
#define gd_hudUseSel                     12       /* BMP  */
#define gd_hudUpSel                      13       /* BMP  */
#define gd_hudDownSel                    14       /* BMP  */
#define gd_gui                           15       /* BMP  */
#define gd_guiMainHs                     16       /* BMP  */
#define gd_guiExitHs                     17       /* BMP  */
#define gd_guiOptionsHs                  18       /* BMP  */
#define gd_guiSaveHs                     19       /* BMP  */
#define gd_guiLoadHs                     20       /* BMP  */
#define gd_guiSlotSel                    21       /* BMP  */
#define gd_COUNT                         22

