/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\GDATA.DAT */
/* Date: Mon Dec 02 15:50:39 2024 */
/* Do not hand edit! */

#define gd_gamePal                       0        /* PAL  */
#define gd_cursor                        1        /* BMP  */
#define gd_hud                           2        /* BMP  */
#define gd_hudhs                         3        /* BMP  */
#define gd_hudGoSel                      4        /* BMP  */
#define gd_hudCloseSel                   5        /* BMP  */
#define gd_hudGiveSel                    6        /* BMP  */
#define gd_hudLookSel                    7        /* BMP  */
#define gd_hudMoveSel                    8        /* BMP  */
#define gd_hudOpenSel                    9        /* BMP  */
#define gd_hudTakeSel                    10       /* BMP  */
#define gd_hudTalkSel                    11       /* BMP  */
#define gd_hudUseSel                     12       /* BMP  */
#define gd_hudUpSel                      13       /* BMP  */
#define gd_hudDownSel                    14       /* BMP  */
#define gd_guiMain                       15       /* BMP  */
#define gd_guiMainHs                     16       /* BMP  */
#define gd_guiExitHs                     17       /* BMP  */
#define gd_guiOptionsHs                  18       /* BMP  */
#define gd_guiSaveHs                     19       /* BMP  */
#define gd_guiLoadHs                     20       /* BMP  */
#define gd_guiSlotSel                    21       /* BMP  */
#define gd_guiAboutSel                   22       /* BMP  */
#define gd_guiExit                       23       /* BMP  */
#define gd_guiExitDosSel                 24       /* BMP  */
#define gd_guiExitSel                    25       /* BMP  */
#define gd_guiExitTitleSel               26       /* BMP  */
#define gd_guiLoadSel                    27       /* BMP  */
#define gd_guiOptions                    28       /* BMP  */
#define gd_guiOptionsSel                 29       /* BMP  */
#define gd_guiSaveSel                    30       /* BMP  */
#define gd_guiSlider                     31       /* BMP  */
#define gd_hudDialogHs                   32       /* BMP  */
#define gd_guiDebug                      33       /* BMP  */
#define gd_guiDebugHs                    34       /* BMP  */
#define gd_gameFont                      35       /* FONT */
#define gd_verdana8                      36       /* FONT */
#define gd_verdana8Bold                  37       /* FONT */
#define gd_verdana9                      38       /* FONT */
#define gd_verdana9Bold                  39       /* FONT */
#define gd_COUNT                         40

