/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\GUI.DAT */
/* Date: Thu Aug 29 19:39:11 2024 */
/* Do not hand edit! */

#define dGui_Box                         0        /* BMP  */
#define dGui_Main                        1        /* BMP  */
#define dGui_MainHs                      2        /* BMP  */
#define dGui_COUNT                       3

