/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\GUI.DAT */
/* Date: Fri Aug 30 15:40:46 2024 */
/* Do not hand edit! */

#define dGui_AboutSel                    0        /* BMP  */
#define dGui_Box                         1        /* BMP  */
#define dGui_Exit                        2        /* BMP  */
#define dGui_ExitDosSel                  3        /* BMP  */
#define dGui_ExitSel                     4        /* BMP  */
#define dGui_ExitTitleSel                5        /* BMP  */
#define dGui_LoadSel                     6        /* BMP  */
#define dGui_Main                        7        /* BMP  */
#define dGui_MainHs                      8        /* BMP  */
#define dGui_Options                     9        /* BMP  */
#define dGui_OptionsSel                  10       /* BMP  */
#define dGui_SaveSel                     11       /* BMP  */
#define dGui_Slider                      12       /* BMP  */
#define dGui_COUNT                       13

