/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\IDATA.DAT */
/* Date: Mon Nov 25 19:36:40 2024 */
/* Do not hand edit! */

#define id_answers                       0        /* BMP  */
#define id_blackBrain                    1        /* BMP  */
#define id_book                          2        /* BMP  */
#define id_brain                         3        /* BMP  */
#define id_califications                 4        /* BMP  */
#define id_cassette                      5        /* BMP  */
#define id_coin                          6        /* BMP  */
#define id_emptyCartridge                7        /* BMP  */
#define id_filledFolder                  8        /* BMP  */
#define id_folder                        9        /* BMP  */
#define id_fullCartridge                 10       /* BMP  */
#define id_gel                           11       /* BMP  */
#define id_guitar                        12       /* BMP  */
#define id_jeans                         13       /* BMP  */
#define id_knife                         14       /* BMP  */
#define id_oat                           15       /* BMP  */
#define id_paintBucket                   16       /* BMP  */
#define id_photocopy                     17       /* BMP  */
#define id_photocopySchedule             18       /* BMP  */
#define id_schedule                      19       /* BMP  */
#define id_shirt                         20       /* BMP  */
#define id_spatula                       21       /* BMP  */
#define id_starClock                     22       /* BMP  */
#define id_starShirt                     23       /* BMP  */
#define id_COUNT                         24

