/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\IDATA.DAT */
/* Date: Wed Nov 27 13:04:57 2024 */
/* Do not hand edit! */

#define id_answers                       0        /* BMP  */
#define id_bathMat                       1        /* BMP  */
#define id_blackBrain                    2        /* BMP  */
#define id_blackStarClock                3        /* BMP  */
#define id_book                          4        /* BMP  */
#define id_bookSheets                    5        /* BMP  */
#define id_brain                         6        /* BMP  */
#define id_califications                 7        /* BMP  */
#define id_cassette                      8        /* BMP  */
#define id_coin                          9        /* BMP  */
#define id_emptyCartridge                10       /* BMP  */
#define id_folder                        11       /* BMP  */
#define id_fullCartridge                 12       /* BMP  */
#define id_fullFolder                    13       /* BMP  */
#define id_gel                           14       /* BMP  */
#define id_guitar                        15       /* BMP  */
#define id_jeans                         16       /* BMP  */
#define id_key                           17       /* BMP  */
#define id_knife                         18       /* BMP  */
#define id_money                         19       /* BMP  */
#define id_oat                           20       /* BMP  */
#define id_openedEmptyCartridge          21       /* BMP  */
#define id_openedFullCartridge           22       /* BMP  */
#define id_paintBucket                   23       /* BMP  */
#define id_photocopy                     24       /* BMP  */
#define id_photocopySchedule             25       /* BMP  */
#define id_schedule                      26       /* BMP  */
#define id_sheet                         27       /* BMP  */
#define id_shirt                         28       /* BMP  */
#define id_spatula                       29       /* BMP  */
#define id_starClock                     30       /* BMP  */
#define id_starShirt                     31       /* BMP  */
#define id_COUNT                         32

