/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\MDATA.DAT */
/* Date: Wed Jan 29 17:07:19 2025 */
/* Do not hand edit! */

#define md_Song01                        0        /* MIDI */
#define md_Song02                        1        /* MIDI */
#define md_Song03                        2        /* MIDI */
#define md_Song04                        3        /* MIDI */
#define md_Song05                        4        /* MIDI */
#define md_Song06                        5        /* MIDI */
#define md_Song07                        6        /* MIDI */
#define md_Song08                        7        /* MIDI */
#define md_Song09                        8        /* MIDI */
#define md_Song10                        9        /* MIDI */
#define md_Song11                        10       /* MIDI */
#define md_Song12                        11       /* MIDI */
#define md_warcomLogo                    12       /* MIDI */
#define md_title                         13       /* MIDI */
#define md_concert                       14       /* MIDI */
#define md_COUNT                         15

