/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\MDATA.DAT */
/* Date: Thu Jan 30 20:32:28 2025 */
/* Do not hand edit! */

#define md_foxtrot                       0        /* MIDI */
#define md_intro                         1        /* MIDI */
#define md_celtic                        2        /* MIDI */
#define md_jazz                          3        /* MIDI */
#define md_elevator                      4        /* MIDI */
#define md_ambience                      5        /* MIDI */
#define md_world                         6        /* MIDI */
#define md_reagge                        7        /* MIDI */
#define md_rockBlues                     8        /* MIDI */
#define md_chunky                        9        /* MIDI */
#define md_city                          10       /* MIDI */
#define md_warcomLogo                    11       /* MIDI */
#define md_title                         12       /* MIDI */
#define md_concert                       13       /* MIDI */
#define md_COUNT                         14

