/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\PDATA.DAT */
/* Date: Mon Sep 09 14:47:00 2024 */
/* Do not hand edit! */

#define pd_plyBackIdle                   0        /* BMP  */
#define pd_plyIdle                       1        /* BMP  */
#define pd_plyTake                       2        /* BMP  */
#define pd_plyTalk01                     3        /* BMP  */
#define pd_plyTalk02                     4        /* BMP  */
#define pd_plyWalk01                     5        /* BMP  */
#define pd_plyWalk02                     6        /* BMP  */
#define pd_COUNT                         7

