/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\PDATA.DAT */
/* Date: Sat Jan 18 19:44:24 2025 */
/* Do not hand edit! */

#define pd_applyOat1                     0        /* BMP  */
#define pd_applyOat2                     1        /* BMP  */
#define pd_applyOat3                     2        /* BMP  */
#define pd_applyOat4                     3        /* BMP  */
#define pd_applyOat5                     4        /* BMP  */
#define pd_applyOat6                     5        /* BMP  */
#define pd_backTalk01                    6        /* BMP  */
#define pd_backTalk02                    7        /* BMP  */
#define pd_backTalk03                    8        /* BMP  */
#define pd_backTalk04                    9        /* BMP  */
#define pd_endOat1                       10       /* BMP  */
#define pd_endOat2                       11       /* BMP  */
#define pd_endOat3                       12       /* BMP  */
#define pd_idle                          13       /* BMP  */
#define pd_surprise                      14       /* BMP  */
#define pd_take                          15       /* BMP  */
#define pd_talk01                        16       /* BMP  */
#define pd_talk02                        17       /* BMP  */
#define pd_talk03                        18       /* BMP  */
#define pd_talk04                        19       /* BMP  */
#define pd_talk05                        20       /* BMP  */
#define pd_talk06                        21       /* BMP  */
#define pd_talk07                        22       /* BMP  */
#define pd_talk08                        23       /* BMP  */
#define pd_talk09                        24       /* BMP  */
#define pd_talk10                        25       /* BMP  */
#define pd_talk11                        26       /* BMP  */
#define pd_walk01                        27       /* BMP  */
#define pd_walk02                        28       /* BMP  */
#define pd_walk03                        29       /* BMP  */
#define pd_walk04                        30       /* BMP  */
#define pd_walk05                        31       /* BMP  */
#define pd_walk06                        32       /* BMP  */
#define pd_washHands01                   33       /* BMP  */
#define pd_washHands02                   34       /* BMP  */
#define pd_washHands03                   35       /* BMP  */
#define pd_COUNT                         36

