/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R00DATA.DAT */
/* Date: Thu Nov 07 15:19:45 2024 */
/* Do not hand edit! */

#define r00d_image                       0        /* BMP  */
#define r00d_hs                          1        /* BMP  */
#define r00d_w                           2        /* BMP  */
#define r00d_COUNT                       3

