/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R01DATA.DAT */
/* Date: Tue Oct 01 14:51:55 2024 */
/* Do not hand edit! */

#define r01d_room01                      0        /* BMP  */
#define r01d_room01hs                    1        /* BMP  */
#define r01d_room01w                     2        /* BMP  */
#define r01d_objCassette                 3        /* BMP  */
#define r01d_objGuitar                   4        /* BMP  */
#define r01d_objStereo01                 5        /* BMP  */
#define r01d_objStereo02                 6        /* BMP  */
#define r01d_objStereo03                 7        /* BMP  */
#define r01d_objStereo04                 8        /* BMP  */
#define r01d_objTable                    9        /* BMP  */
#define r01d_COUNT                       10

