/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R01DATA.DAT */
/* Date: Wed Sep 11 16:25:32 2024 */
/* Do not hand edit! */

#define r01d_room01                      0        /* BMP  */
#define r01d_room01hs                    1        /* BMP  */
#define r01d_room01w                     2        /* BMP  */
#define r01d_song01                      3        /* MIDI */
#define r01d_objCassette                 4        /* BMP  */
#define r01d_objGuitar                   5        /* BMP  */
#define r01d_objStereo01                 6        /* BMP  */
#define r01d_objStereo02                 7        /* BMP  */
#define r01d_objStereo03                 8        /* BMP  */
#define r01d_objStereo04                 9        /* BMP  */
#define r01d_objTable                    10       /* BMP  */
#define r01d_COUNT                       11

