/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R01DATA.DAT */
/* Date: Mon Sep 09 15:12:16 2024 */
/* Do not hand edit! */

#define r01d_room01                      0        /* BMP  */
#define r01d_room01hs                    1        /* BMP  */
#define r01d_room01w                     2        /* BMP  */
#define r01d_room01f                     3        /* BMP  */
#define r01d_song01                      4        /* MIDI */
#define r01d_objCassette                 5        /* BMP  */
#define r01d_objGuitar                   6        /* BMP  */
#define r01d_objStereo01                 7        /* BMP  */
#define r01d_objStereo02                 8        /* BMP  */
#define r01d_objStereo03                 9        /* BMP  */
#define r01d_objStereo04                 10       /* BMP  */
#define r01d_COUNT                       11

