/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R02DATA.DAT */
/* Date: Mon Sep 09 12:57:36 2024 */
/* Do not hand edit! */

#define r02d_image                       0        /* BMP  */
#define r02d_hs                          1        /* BMP  */
#define r02d_w                           2        /* BMP  */
#define r02d_objBathDoor                 3        /* BMP  */
#define r02d_COUNT                       4

