/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R03DATA.DAT */
/* Date: Tue Dec 10 16:12:39 2024 */
/* Do not hand edit! */

#define r03d_image                       0        /* BMP  */
#define r03d_hs                          1        /* BMP  */
#define r03d_w                           2        /* BMP  */
#define r03d_objBath                     3        /* BMP  */
#define r03d_objBathClosetOpen           4        /* BMP  */
#define r03d_objBathDoorOpen             5        /* BMP  */
#define r03d_objGel                      6        /* BMP  */
#define r03d_objBathMat                  7        /* BMP  */
#define r03d_COUNT                       8

