/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R03DATA.DAT */
/* Date: Wed Sep 11 17:34:37 2024 */
/* Do not hand edit! */

#define r03d_image                       0        /* BMP  */
#define r03d_hs                          1        /* BMP  */
#define r03d_w                           2        /* BMP  */
#define r03d_song                        3        /* MIDI */
#define r03d_objBath                     4        /* BMP  */
#define r03d_objBathClosetOpen           5        /* BMP  */
#define r03d_objBathDoor                 6        /* BMP  */
#define r03d_objGel                      7        /* BMP  */
#define r03d_COUNT                       8

