/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R04DATA.DAT */
/* Date: Sun Jan 05 15:39:41 2025 */
/* Do not hand edit! */

#define r04d_image                       0        /* BMP  */
#define r04d_hs                          1        /* BMP  */
#define r04d_w                           2        /* BMP  */
#define r04d_objIdle                     3        /* BMP  */
#define r04d_objStarClock                4        /* BMP  */
#define r04d_objSpatula                  5        /* BMP  */
#define r04d_objClosetOpen               6        /* BMP  */
#define r04d_objOat                      7        /* BMP  */
#define r04d_objTalk1                    8        /* BMP  */
#define r04d_objTalk2                    9        /* BMP  */
#define r04d_objTalk3                    10       /* BMP  */
#define r04d_objTalk4                    11       /* BMP  */
#define r04d_objTalk5                    12       /* BMP  */
#define r04d_objTalk6                    13       /* BMP  */
#define r04d_objTalk7                    14       /* BMP  */
#define r04d_objTalk8                    15       /* BMP  */
#define r04d_objTalk9                    16       /* BMP  */
#define r04d_objTable                    17       /* BMP  */
#define r04d_COUNT                       18

