/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R04DATA.DAT */
/* Date: Wed Sep 11 17:36:56 2024 */
/* Do not hand edit! */

#define r04d_image                       0        /* BMP  */
#define r04d_hs                          1        /* BMP  */
#define r04d_w                           2        /* BMP  */
#define r04d_song                        3        /* MIDI */
#define r04d_objBath                     4        /* BMP  */
#define r04d_objBathClosetOpen           5        /* BMP  */
#define r04d_objBathDoor                 6        /* BMP  */
#define r04d_objGel                      7        /* BMP  */
#define r04d_objFatherRead               8        /* BMP  */
#define r04d_objFatherIdle               9        /* BMP  */
#define r04d_objFatherTalk               10       /* BMP  */
#define r04d_COUNT                       11

