/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R04DATA.DAT */
/* Date: Wed Dec 25 11:52:37 2024 */
/* Do not hand edit! */

#define r04d_image                       0        /* BMP  */
#define r04d_hs                          1        /* BMP  */
#define r04d_w                           2        /* BMP  */
#define r04d_objFatherRead               3        /* BMP  */
#define r04d_objFatherIdle               4        /* BMP  */
#define r04d_objFatherTalk               5        /* BMP  */
#define r04d_objStarClock                6        /* BMP  */
#define r04d_objSpatula                  7        /* BMP  */
#define r04d_objClosetOpen               8        /* BMP  */
#define r04d_objOat                      9        /* BMP  */
#define r04d_COUNT                       10

