/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R05DATA.DAT */
/* Date: Fri Dec 13 11:54:54 2024 */
/* Do not hand edit! */

#define r05d_image                       0        /* BMP  */
#define r05d_hs                          1        /* BMP  */
#define r05d_w                           2        /* BMP  */
#define r05d_objPrintedSchPhoto          3        /* BMP  */
#define r05d_objSheets                   4        /* BMP  */
#define r05d_objPrintedSch               5        /* BMP  */
#define r05d_objPrintedPhoto             6        /* BMP  */
#define r05d_objPhotocopy                7        /* BMP  */
#define r05d_objCartridgeFull            8        /* BMP  */
#define r05d_objCartridgeEmpty           9        /* BMP  */
#define r05d_COUNT                       10

