/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R05DATA.DAT */
/* Date: Fri Nov 08 16:07:08 2024 */
/* Do not hand edit! */

#define r05d_image                       0        /* BMP  */
#define r05d_hs                          1        /* BMP  */
#define r05d_w                           2        /* BMP  */
#define r05d_COUNT                       3

