/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R06DATA.DAT */
/* Date: Fri Nov 08 16:00:12 2024 */
/* Do not hand edit! */

#define r06d_image                       0        /* BMP  */
#define r06d_hs                          1        /* BMP  */
#define r06d_w                           2        /* BMP  */
#define r06d_COUNT                       3

