/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R06DATA.DAT */
/* Date: Mon Dec 23 11:54:55 2024 */
/* Do not hand edit! */

#define r06d_image                       0        /* BMP  */
#define r06d_hs                          1        /* BMP  */
#define r06d_w                           2        /* BMP  */
#define r06d_objBathMatIn                3        /* BMP  */
#define r06d_objBathMatOut               4        /* BMP  */
#define r06d_objKey                      5        /* BMP  */
#define r06d_objMaintDoorOpen            6        /* BMP  */
#define r06d_objMaintDoorOpenLight       7        /* BMP  */
#define r06d_COUNT                       8

