/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R07DATA.DAT */
/* Date: Thu Dec 05 19:32:32 2024 */
/* Do not hand edit! */

#define r07d_image                       0        /* BMP  */
#define r07d_hs                          1        /* BMP  */
#define r07d_w                           2        /* BMP  */
#define r07d_objTable                    3        /* BMP  */
#define r07d_objBrain                    4        /* BMP  */
#define r07d_COUNT                       5

