/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R08DATA.DAT */
/* Date: Mon Dec 30 19:26:07 2024 */
/* Do not hand edit! */

#define r08d_image                       0        /* BMP  */
#define r08d_hs                          1        /* BMP  */
#define r08d_w                           2        /* BMP  */
#define r08d_objIdle                     3        /* BMP  */
#define r08d_objTalk1                    4        /* BMP  */
#define r08d_objTalk2                    5        /* BMP  */
#define r08d_objTalk3                    6        /* BMP  */
#define r08d_objTalk4                    7        /* BMP  */
#define r08d_objTalk5                    8        /* BMP  */
#define r08d_objTalk6                    9        /* BMP  */
#define r08d_objTalk7                    10       /* BMP  */
#define r08d_objTalk8                    11       /* BMP  */
#define r08d_objTalk9                    12       /* BMP  */
#define r08d_objPlay1                    13       /* BMP  */
#define r08d_objPlay2                    14       /* BMP  */
#define r08d_objPlay3                    15       /* BMP  */
#define r08d_objPlay4                    16       /* BMP  */
#define r08d_objPlay5                    17       /* BMP  */
#define r08d_objPlay6                    18       /* BMP  */
#define r08d_COUNT                       19

