/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R09DATA.DAT */
/* Date: Sat Dec 07 16:48:40 2024 */
/* Do not hand edit! */

#define r09d_image                       0        /* BMP  */
#define r09d_hs                          1        /* BMP  */
#define r09d_w                           2        /* BMP  */
#define r09d_objBench                    3        /* BMP  */
#define r09d_COUNT                       4

