/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R09DATA.DAT */
/* Date: Sun Dec 22 17:52:52 2024 */
/* Do not hand edit! */

#define r09d_image                       0        /* BMP  */
#define r09d_hs                          1        /* BMP  */
#define r09d_w                           2        /* BMP  */
#define r09d_objBench                    3        /* BMP  */
#define r09d_objLocker1Open              4        /* BMP  */
#define r09d_objLocker2Open              5        /* BMP  */
#define r09d_objLocker3Open              6        /* BMP  */
#define r09d_objShirt                    7        /* BMP  */
#define r09d_objJeans                    8        /* BMP  */
#define r09d_COUNT                       9

