/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R10DATA.DAT */
/* Date: Sun Dec 22 17:55:48 2024 */
/* Do not hand edit! */

#define r10d_image                       0        /* BMP  */
#define r10d_hs                          1        /* BMP  */
#define r10d_w                           2        /* BMP  */
#define r10d_objMaintClosetOpen          3        /* BMP  */
#define r10d_objPaintBucket              4        /* BMP  */
#define r10d_objDoorOpen                 5        /* BMP  */
#define r10d_COUNT                       6

