/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R10DATA.DAT */
/* Date: Mon Nov 18 15:24:55 2024 */
/* Do not hand edit! */

#define r10d_image                       0        /* BMP  */
#define r10d_hs                          1        /* BMP  */
#define r10d_w                           2        /* BMP  */
#define r10d_COUNT                       3

