/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R10DATA.DAT */
/* Date: Mon Jan 13 16:29:24 2025 */
/* Do not hand edit! */

#define r10d_image                       0        /* BMP  */
#define r10d_hs                          1        /* BMP  */
#define r10d_w                           2        /* BMP  */
#define r10d_objMaintClosetOpen          3        /* BMP  */
#define r10d_objPaintBucket              4        /* BMP  */
#define r10d_objDoorOpen                 5        /* BMP  */
#define r10d_objBox                      6        /* BMP  */
#define r10d_objBathMat                  7        /* BMP  */
#define r10d_COUNT                       8

