/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R11DATA.DAT */
/* Date: Wed Dec 04 16:13:08 2024 */
/* Do not hand edit! */

#define r11d_image                       0        /* BMP  */
#define r11d_hs                          1        /* BMP  */
#define r11d_w                           2        /* BMP  */
#define r11d_COUNT                       3

