/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R11DATA.DAT */
/* Date: Mon Dec 30 14:53:49 2024 */
/* Do not hand edit! */

#define r11d_image                       0        /* BMP  */
#define r11d_hs                          1        /* BMP  */
#define r11d_w                           2        /* BMP  */
#define r11d_objReading1                 3        /* BMP  */
#define r11d_objReading2                 4        /* BMP  */
#define r11d_objReading3                 5        /* BMP  */
#define r11d_objReading4                 6        /* BMP  */
#define r11d_objTalk1                    7        /* BMP  */
#define r11d_objTalk2                    8        /* BMP  */
#define r11d_objTalk3                    9        /* BMP  */
#define r11d_objTalk4                    10       /* BMP  */
#define r11d_objTalk5                    11       /* BMP  */
#define r11d_objTalk6                    12       /* BMP  */
#define r11d_objTalk7                    13       /* BMP  */
#define r11d_objTalk8                    14       /* BMP  */
#define r11d_objTalk9                    15       /* BMP  */
#define r11d_objSurprise                 16       /* BMP  */
#define r11d_objTake                     17       /* BMP  */
#define r11d_COUNT                       18

