/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R12DATA.DAT */
/* Date: Wed Nov 27 19:13:30 2024 */
/* Do not hand edit! */

#define r12d_image                       0        /* BMP  */
#define r12d_hs                          1        /* BMP  */
#define r12d_w                           2        /* BMP  */
#define r12d_COUNT                       3

