/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R12DATA.DAT */
/* Date: Fri Jan 17 17:04:21 2025 */
/* Do not hand edit! */

#define r12d_image                       0        /* BMP  */
#define r12d_hs                          1        /* BMP  */
#define r12d_w                           2        /* BMP  */
#define r12d_objHand                     3        /* BMP  */
#define r12d_objHandExam                 4        /* BMP  */
#define r12d_objDoorOpen                 5        /* BMP  */
#define r12d_objFrontDoor                6        /* BMP  */
#define r12d_COUNT                       7

