/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R12DATA.DAT */
/* Date: Sun Dec 22 17:56:27 2024 */
/* Do not hand edit! */

#define r12d_image                       0        /* BMP  */
#define r12d_hs                          1        /* BMP  */
#define r12d_w                           2        /* BMP  */
#define r12d_objHand                     3        /* BMP  */
#define r12d_objHandExam                 4        /* BMP  */
#define r12d_COUNT                       5

