/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R13DATA.DAT */
/* Date: Mon Jan 20 15:33:11 2025 */
/* Do not hand edit! */

#define r13d_image                       0        /* BMP  */
#define r13d_hs                          1        /* BMP  */
#define r13d_w                           2        /* BMP  */
#define r13d_COUNT                       3

