/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R13DATA.DAT */
/* Date: Wed Jan 22 14:39:27 2025 */
/* Do not hand edit! */

#define r13d_image                       0        /* BMP  */
#define r13d_hs                          1        /* BMP  */
#define r13d_walk                        2        /* BMP  */
#define r13d_objSpeakers1                3        /* BMP  */
#define r13d_objSpeakers2                4        /* BMP  */
#define r13d_objSpeakers3                5        /* BMP  */
#define r13d_objSpeakers4                6        /* BMP  */
#define r13d_objCrowd1                   7        /* BMP  */
#define r13d_objCrowd2                   8        /* BMP  */
#define r13d_objDrums1                   9        /* BMP  */
#define r13d_objDrums2                   10       /* BMP  */
#define r13d_objDrums3                   11       /* BMP  */
#define r13d_objDrums4                   12       /* BMP  */
#define r13d_objGuitar11                 13       /* BMP  */
#define r13d_objGuitar12                 14       /* BMP  */
#define r13d_objGuitar21                 15       /* BMP  */
#define r13d_objGuitar22                 16       /* BMP  */
#define r13d_COUNT                       17

