/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\R13DATA.DAT */
/* Date: Tue Jan 21 11:33:38 2025 */
/* Do not hand edit! */

#define r13d_image                       0        /* BMP  */
#define r13d_hs                          1        /* BMP  */
#define r13d_walk                        2        /* BMP  */
#define r13d_COUNT                       3

