/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\SDATA.DAT */
/* Date: Wed Feb 12 16:59:34 2025 */
/* Do not hand edit! */

#define sd_approved                      0        /* SAMP */
#define sd_cassettePlay                  1        /* SAMP */
#define sd_cassettePut                   2        /* SAMP */
#define sd_cassetteSong                  3        /* SAMP */
#define sd_closetClose                   4        /* SAMP */
#define sd_closetOpen                    5        /* SAMP */
#define sd_completed                     6        /* SAMP */
#define sd_computerBoot                  7        /* SAMP */
#define sd_dogBarf                       8        /* SAMP */
#define sd_doorClose                     9        /* SAMP */
#define sd_doorLockerOpen                10       /* SAMP */
#define sd_doorOpen                      11       /* SAMP */
#define sd_greasy                        12       /* SAMP */
#define sd_jump                          13       /* SAMP */
#define sd_keyFall                       14       /* SAMP */
#define sd_knife                         15       /* SAMP */
#define sd_lidClose                      16       /* SAMP */
#define sd_lidOpen                       17       /* SAMP */
#define sd_lockerClose                   18       /* SAMP */
#define sd_lockerOpen                    19       /* SAMP */
#define sd_money                         20       /* SAMP */
#define sd_msDosJingle                   21       /* SAMP */
#define sd_paint                         22       /* SAMP */
#define sd_paper                         23       /* SAMP */
#define sd_printer                       24       /* SAMP */
#define sd_switch                        25       /* SAMP */
#define sd_take                          26       /* SAMP */
#define sd_take2                         27       /* SAMP */
#define sd_toiletFlush                   28       /* SAMP */
#define sd_unglue                        29       /* SAMP */
#define sd_urinating                     30       /* SAMP */
#define sd_w95Error                      31       /* SAMP */
#define sd_washHands                     32       /* SAMP */
#define sd_win95Startup                  33       /* SAMP */
#define sd_COUNT                         34

