/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\SDATA.DAT */
/* Date: Sat Jan 04 11:12:59 2025 */
/* Do not hand edit! */

#define sd_doorClose                     0        /* SAMP */
#define sd_doorOpen                      1        /* SAMP */
#define sd_greasy                        2        /* SAMP */
#define sd_jump                          3        /* SAMP */
#define sd_knife                         4        /* SAMP */
#define sd_lockerClose                   5        /* SAMP */
#define sd_lockerOpen                    6        /* SAMP */
#define sd_paint                         7        /* SAMP */
#define sd_printer                       8        /* SAMP */
#define sd_switch                        9        /* SAMP */
#define sd_take                          10       /* SAMP */
#define sd_w95Error                      11       /* SAMP */
#define sd_win95Startup                  12       /* SAMP */
#define sd_COUNT                         13

