/* Allegro datafile object indexes, produced by grabber v4.2.1, MSVC */
/* Datafile: d:\Instalables\Proyectos\Programacion DOS\entorno DGK4DOS\env\code\game\SDATA.DAT */
/* Date: Tue Jan 07 10:42:17 2025 */
/* Do not hand edit! */

#define sd_closetClose                   0        /* SAMP */
#define sd_closetOpen                    1        /* SAMP */
#define sd_doorClose                     2        /* SAMP */
#define sd_doorLockerOpen                3        /* SAMP */
#define sd_doorOpen                      4        /* SAMP */
#define sd_greasy                        5        /* SAMP */
#define sd_jump                          6        /* SAMP */
#define sd_keyFall                       7        /* SAMP */
#define sd_knife                         8        /* SAMP */
#define sd_lockerClose                   9        /* SAMP */
#define sd_lockerOpen                    10       /* SAMP */
#define sd_paint                         11       /* SAMP */
#define sd_printer                       12       /* SAMP */
#define sd_switch                        13       /* SAMP */
#define sd_take                          14       /* SAMP */
#define sd_take2                         15       /* SAMP */
#define sd_w95Error                      16       /* SAMP */
#define sd_win95Startup                  17       /* SAMP */
#define sd_COUNT                         18

